Update nasl_http2.c to use long integer for certain Curl requests
When compiling nasl_http2.c as part of security/openvas on FreeBSD using the customary FreeBSD Ports Collection, these error messages appeared after Curl was updated to 8.16.0 in the Ports Collection:

/construction/xports/security/openvas/work/openvas-scanner-23.20.1/nasl/nasl_http2.c:380:7: error: call to '_curl_easy_setopt_err_long' declared with 'warning' attribute: curl_easy_setopt expects a long argument [-Werror,-Wattribute-warning]
380 | curl_easy_setopt (handle, CURLOPT_HTTPGET, 1);
| ^
/usr/local/include/curl/typecheck-gcc.h:50:15: note: expanded from macro 'curl_easy_setopt'
50 | _curl_easy_setopt_err_long();
| ^
/construction/xports/security/openvas/work/openvas-scanner-23.20.1/nasl/nasl_http2.c:369:7: error: call to '_curl_easy_setopt_err_long' declared with 'warning' attribute: curl_easy_setopt expects a long argument [-Werror,-Wattribute-warning]
369 | curl_easy_setopt (handle, CURLOPT_NOBODY, 1);
| ^
/usr/local/include/curl/typecheck-gcc.h:50:15: note: expanded from macro 'curl_easy_setopt'
50 | _curl_easy_setopt_err_long();
| ^
2 errors generated.
ninja: build stopped: subcommand failed.
===> Compilation failed unexpectedly.

Solved by simply adding an L suffix to the final parameter.